# Imagen base de Python
FROM python:3.11-slim

# Variables recomendadas
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY requirements/ ./requirements

# Instalar dependencias del frontend
RUN pip install --no-cache-dir -r requirements/frontend.txt

# Copiar todo el proyecto
COPY . .

# Puerto de Streamlit
EXPOSE 8501

# Ejecutar frontend
CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]