# Imagen base ligera de Python
FROM python:3.11-slim

# Evitar archivos .pyc y forzar logs inmediatos
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar dependencias primero (mejor uso de cache)
COPY requirements/ ./requirements

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements/api.txt

# Copiar todo el proyecto
COPY . .

# Exponer puerto de la API
EXPOSE 5000

# Inicializar base de datos y luego arrancar API
CMD ["sh", "-c", "python scripts/init_db.py && python api/api.py"]